export enum ROUTES {
  LoginScreen = 'LoginScreen',
  CreateAccount = 'CreateAccount',
  AuthStack = 'AuthLogin',
  TabGroup = 'TabGroup',
  LandingScreen = 'LandingScreen',
  ScreenBridge = 'ScreenBridge',
  HomeScreen = 'HomeScreen',
  HomeStack = 'HomeStack',
  MYCAMPAIGN = 'MYCAMPAIGN',
  Result = 'Result',
  ShowResults = 'ShowResults',
  ResultStack = 'ResultStack',
  Settings = 'Settings',
  Schedule = 'Schedule',
}
