export const strings: object | string | any = {
  Email: 'Email',
  Password: 'Password',
  EmailPlaceHolder: 'example@gmail.com',
  PasswordPlaceHolder: 'Enter Your Password',
  ForgotPassword: 'Forgot Password?',
  Donthaveaccount: 'Don’t have an account?',
  Facebook: 'Signup with Facebook',
  GoogleG: 'Signup with Google',
  SignUp: 'Sign Up',
  SignIn: 'Sign In',
  Welcome: 'Hi, Welcome Back! 👋',
  always: 'always',
  UserNamePlacholder: 'Enter Your Username',
  PhoneNumberPlacholder: 'Enter Your Phone Number',
  Account: 'Already have an account?',
  Login: 'Login',
  CreateAccount: 'Create an account',
  ConnectFriends: 'Connect with your friends today!',
  validationMessageRequest: (params: string) => {
    return `Please Enter Valid ${params}`;
  },
  FirebaseErrorMessage: {
    EmailAlreadyUser: 'auth/email-already-in-use',
    Error: 'Error',
  },
  BRCL: 'borderColor',
  green: 'green',
  grey: 'grey',
  CL: 'color',
  Quit: 'Quit',
  SubmitQuiz: 'Submit Quiz',
  next: 'next',
  QuizTitle: 'Quiz Title',
  Question:"Question",
  Automatic:"automatic"
};
