export const type = {
    FIRST_NAME: "FIRST_NAME",
    EMAIL: "EMAIL",
    PASSWORD: "PASSWORD",
    PHONE_NUMBER: "PHONE_NUMBER",
    SECURE_TEXTENTRY: "SECURE_TEXTENTRY",
    QUESTION_LOADING: "QUESTION_LOADING",
    QUESTION_DATA: "QUESTION_DATA",
    QUESTION_ERROR: "QUESTION_ERROR",
    INCREASE_INDEX: "INCREASE_INDEX",
    ON_SUBMIT_ANSWER: "ON_SUBMIT_ANSWER",
    ON_NEXT: "ON_NEXT",
    FINAL_SUBMIT_ANSWER: "FINAL_SUBMIT_ANSWER",
    ON_SELECTOPTION: "ON_SELECTOPTION",
    JUMP_INDEX:"JUMP_INDEX"
}