name: Review Source Code

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '18.19.0'

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm install --immutable
      - name: Check for unused dependencies
        run: npm run depcheck

  tsc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Compile source code
        run: npm run tsc --noEmit

  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm install --immutable
      - name: Check format of source code
        run: npm run prettier -c .

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Lint source code
        run: npm run eslint -f rdjson -o eslint-report.rdjson.json .
      - name: Post Lint source code
        run: cat eslint-report.rdjson.json | reviewdog -f=rdjson -diff="git diff FETCH_HEAD" -name=eslint -reporter=github-pr-check
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Run test suite
        run: npm run test --silent --ci --coverage
